version: "3.9"
services:
  wol:
    build:
      context: ./wol
    image: cz0r3k/wake_on_lan
    network_mode: "host"
    environment:
      - WEB_PORT=${WEB_PORT}
      - SENDING_PORT=${SENDING_PORT}
      - RECEIVING_PORT=${RECEIVING_PORT}
      - BROADCAST_IP=${BROADCAST_IP}
      - MAC=${MAC}
    restart: always
